Opening ABIN00000000.1.faa...
Forward Blasting to subject proteome...
Back-Blasting hits to query proteome...
22:00:00
Opening AL123456.3.faa...
Forward Blasting to subject proteome...
22:00:08
Opening CP000431.1.faa...
Forward Blasting to subject proteome...
22:00:08
Opening CP000432.1.faa...
Forward Blasting to subject proteome...
22:00:09
Opening CP001220.1.faa...
Forward Blasting to subject proteome...
22:00:09
Opening SteriodQueryV3.faa...
Forward Blasting to subject proteome...
BLAST Database error: No alias or index file found for protein database [SteriodQueryV3.faa] in search path [/Users/lee/Dropbox/Repositories/BackBLAST_Reciprocal_BLAST::]
Traceback (most recent call last):
  File "BackBLAST.py", line 131, in <module>
    BLASTOut = runBLAST(queryFile, BLASTDBFile) # Forward BLASTs from query protien to subject proteome
  File "BackBLAST.py", line 51, in runBLAST
    BLASTOut = subprocess.check_output(["blastp", "-db", BLASTDBFile, "-query", query, "-evalue", "1e-40", "-num_threads", "16", "-outfmt", "10 qseqid sseqid pident evalue qcovhsp score"]) # Runs BLASTp and save output to a string. Blastp is set to output csv which can be parsed.
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['blastp', '-db', 'SteriodQueryV3.faa', '-query', 'SteriodQueryV3.faa', '-evalue', '1e-40', '-num_threads', '16', '-outfmt', '10 qseqid sseqid pident evalue qcovhsp score']' returned non-zero exit status 2
22:00:09
22:00:09
